[package]
name = "zypp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpgme = "0.11.0"
libsolv-sys = "0.1.0"
thiserror = "1.0.40"
tokyo = "1.0.0"
